export const examOptions = [
  {
    category: "Popular Exams",
    options: [
      {
        title: "CUET",
        description: "For B.Com/BBA/BA Economics in central universities",
        icon: "School",
        color: "blue-600",
        path: "https://cuet.samarth.ac.in/",
      },
      {
        title: "IPMAT",
        description: "For IIM Indore & other IIMs' 5-year BBA+MBA course",
        icon: "GraduationCap",
        color: "indigo-600",
        path: "https://www.iimidr.ac.in/",
      },
      {
        title: "NPAT",
        description: "For NMIMS Mumbai (BBA, B.Com, Branding)",
        icon: "School",
        color: "purple-600",
        path: "https://www.nmims.edu/",
      },
      {
        title: "SET",
        description: "For Symbiosis (BBA, Eco, Law)",
        icon: "School",
        color: "red-600",
        path: "https://set-test.org/",
      },
      {
        title: "CLAT",
        description: "For Law (BA LLB, BBA LLB)",
        icon: "Scale",
        color: "green-600",
        path: "https://consortiumofnlus.ac.in/",
      },
      {
        title: "CA Foundation",
        description: "First step for Chartered Accountancy",
        icon: "Calculator",
        color: "blue-600",
        path: "https://www.icai.org/",
      },
      {
        title: "ICMAI Foundation",
        description: "For Cost & Management Accounting",
        icon: "Calculator",
        color: "orange-600",
        path: "https://icmai.in/",
      },
      {
        title: "CS Foundation",
        description: "For Company Secretary (CS)",
        icon: "Briefcase",
        color: "green-600",
        path: "https://www.icsi.edu/",
      },
    ],
  },
  {
    category: "Specialized Exams",
    options: [
      {
        title: "ATMA",
        description: "For BBA/MBA in some B-schools",
        icon: "School",
        color: "blue-600",
        path: "https://www.atmaaims.com/",
      },
      {
        title: "ACET",
        description: "For Actuarial Science",
        icon: "Calculator",
        color: "purple-600",
        path: "https://www.actuariesindia.org/",
      },
      {
        title: "ISBF Entrance",
        description: "Economics, Finance (LSE curriculum)",
        icon: "School",
        color: "red-600",
        path: "https://www.isbf.edu.in/",
      },
      {
        title: "FLAME Entrance",
        description: "For liberal education in business and finance",
        icon: "School",
        color: "green-600",
        path: "https://www.flame.edu.in/",
      },
      {
        title: "Ashoka University Test",
        description: "For Economics, Finance, etc.",
        icon: "School",
        color: "blue-600",
        path: "https://www.ashoka.edu.in/",
      },
      {
        title: "Christ University Entrance",
        description: "For B.Com/BBA etc.",
        icon: "School",
        color: "indigo-600",
        path: "https://christuniversity.in/",
      },
    ],
  },
];

export const degreeOptions = [
  {
    category: "Popular Degrees",
    options: [
      {
        title: "B.Com (General)",
        description: "Bachelor of Commerce - General",
        icon: "GraduationCap",
        color: "blue-600",
        path: "/career/commerce/bcom",
      },
      {
        title: "B.Com (Hons)",
        description: "Bachelor of Commerce - Honors",
        icon: "GraduationCap",
        color: "indigo-600",
        path: "/career/commerce/bcom-hons",
      },
      {
        title: "BBA",
        description: "Bachelor of Business Administration",
        icon: "Briefcase",
        color: "purple-600",
        path: "/career/commerce/bba",
      },
      {
        title: "BBA Specializations",
        description: "HR/Finance/Marketing/IB",
        icon: "Briefcase",
        color: "red-600",
        path: "/career/commerce/bba-specializations",
      },
      {
        title: "BA Economics",
        description: "Bachelor of Arts in Economics",
        icon: "ChartBar",
        color: "green-600",
        path: "/career/commerce/economics",
      },
      {
        title: "BBE",
        description: "Bachelor of Business Economics",
        icon: "ChartBar",
        color: "blue-600",
        path: "/career/commerce/bbe",
      },
      {
        title: "BMS",
        description: "Bachelor of Management Studies",
        icon: "Briefcase",
        color: "orange-600",
        path: "/career/commerce/bms",
      },
      {
        title: "BBA LLB / B.Com LLB",
        description: "Law + Commerce Integrated Programs",
        icon: "Scale",
        color: "purple-600",
        path: "/career/commerce/law",
      },
    ],
  },
  {
    category: "Professional Courses",
    options: [
      {
        title: "CA",
        description: "Chartered Accountancy",
        icon: "Calculator",
        color: "blue-600",
        path: "/career/commerce/ca",
      },
      {
        title: "CMA",
        description: "Cost & Management Accounting",
        icon: "Calculator",
        color: "green-600",
        path: "/career/commerce/cma",
      },
      {
        title: "CS",
        description: "Company Secretary",
        icon: "Briefcase",
        color: "red-600",
        path: "/career/commerce/cs",
      },
      {
        title: "CFA",
        description: "Chartered Financial Analyst",
        icon: "ChartBar",
        color: "purple-600",
        path: "/career/commerce/cfa",
      },
      {
        title: "FRM",
        description: "Financial Risk Manager",
        icon: "Shield",
        color: "blue-600",
        path: "/career/commerce/frm",
      },
      {
        title: "Actuarial Science",
        description: "BSc + ACET based",
        icon: "Calculator",
        color: "indigo-600",
        path: "/career/commerce/actuarial",
      },
    ],
  },
  {
    category: "Specialized Programs",
    options: [
      {
        title: "BIBF",
        description: "Bachelor in International Business and Finance",
        icon: "Plane",
        color: "blue-600",
        path: "/career/commerce/bibf",
      },
      {
        title: "BBA Aviation",
        description: "Aviation Management",
        icon: "Plane",
        color: "red-600",
        path: "/career/commerce/aviation",
      },
      {
        title: "BBA Digital Marketing",
        description: "Digital Marketing Management",
        icon: "Share2",
        color: "purple-600",
        path: "/career/commerce/digital-marketing",
      },
      {
        title: "BBA Tourism & Hospitality",
        description: "Tourism and Hospitality Management",
        icon: "Home",
        color: "green-600",
        path: "/career/commerce/tourism",
      },
      {
        title: "BBA Banking & Insurance",
        description: "Banking and Insurance Management",
        icon: "Banknote",
        color: "blue-600",
        path: "/career/commerce/banking",
      },
      {
        title: "BBA Business Analytics",
        description: "Business Analytics and Intelligence",
        icon: "ChartBar",
        color: "orange-600",
        path: "/career/commerce/analytics",
      },
    ],
  },
];

export const careerOptions = [
  {
    category: "Business & Finance",
    options: [
      {
        title: "Chartered Accountant",
        description: "Financial Accounting and Auditing",
        icon: "Calculator",
        color: "blue-600",
        path: "/career/commerce/ca",
      },
      {
        title: "Investment Banker",
        description: "Corporate Finance and Investments",
        icon: "ChartBar",
        color: "green-600",
        path: "/career/commerce/investment-banker",
      },
      {
        title: "Financial Analyst",
        description: "Investment and Market Analysis",
        icon: "ChartBar",
        color: "purple-600",
        path: "/career/commerce/financial-analyst",
      },
      {
        title: "Tax Consultant",
        description: "Taxation and Compliance",
        icon: "Calculator",
        color: "red-600",
        path: "/career/commerce/tax-consultant",
      },
      {
        title: "Auditor",
        description: "Financial Audit and Assurance",
        icon: "Calculator",
        color: "blue-600",
        path: "/career/commerce/auditor",
      },
      {
        title: "Stock Market Trader",
        description: "Securities Trading and Analysis",
        icon: "ChartBar",
        color: "green-600",
        path: "/career/commerce/stock-trader",
      },
      {
        title: "Insurance Advisor",
        description: "Insurance Products and Services",
        icon: "Shield",
        color: "blue-600",
        path: "/career/commerce/insurance-advisor",
      },
      {
        title: "Bank PO",
        description: "Banking Operations and Management",
        icon: "Banknote",
        color: "purple-600",
        path: "/career/commerce/bank-po",
      },
    ],
  },
  {
    category: "Management & Corporate",
    options: [
      {
        title: "HR Manager",
        description: "Human Resource Management",
        icon: "Users",
        color: "blue-600",
        path: "/career/commerce/hr-manager",
      },
      {
        title: "Marketing Manager",
        description: "Brand and Product Management",
        icon: "TrendingUp",
        color: "red-600",
        path: "/career/commerce/marketing-manager",
      },
      {
        title: "Business Analyst",
        description: "Business Process Analysis",
        icon: "ChartBar",
        color: "purple-600",
        path: "/career/commerce/business-analyst",
      },
      {
        title: "Operations Manager",
        description: "Business Operations Management",
        icon: "Settings",
        color: "green-600",
        path: "/career/commerce/operations-manager",
      },
      {
        title: "Supply Chain Manager",
        description: "Logistics and Supply Chain",
        icon: "Truck",
        color: "blue-600",
        path: "/career/commerce/supply-chain",
      },
      {
        title: "Entrepreneur",
        description: "Startup and Business Ownership",
        icon: "Rocket",
        color: "orange-600",
        path: "/career/commerce/entrepreneur",
      },
      {
        title: "Product Manager",
        description: "Product Development and Strategy",
        icon: "Box",
        color: "purple-600",
        path: "/career/commerce/product-manager",
      },
      {
        title: "Digital Marketer",
        description: "Online Marketing and Strategy",
        icon: "Share2",
        color: "blue-600",
        path: "/career/commerce/digital-marketer",
      },
    ],
  },
  {
    category: "Law & Policy",
    options: [
      {
        title: "Corporate Lawyer",
        description: "Corporate Legal Advisory",
        icon: "Scale",
        color: "blue-600",
        path: "/career/commerce/corporate-lawyer",
      },
      {
        title: "Legal Advisor",
        description: "Legal Consultation and Guidance",
        icon: "Scale",
        color: "purple-600",
        path: "/career/commerce/legal-advisor",
      },
      {
        title: "Compliance Officer",
        description: "Regulatory Compliance Management",
        icon: "Shield",
        color: "green-600",
        path: "/career/commerce/compliance-officer",
      },
      {
        title: "Civil Services",
        description: "IAS, IFS, and other government services",
        icon: "Building2",
        color: "red-600",
        path: "/career/commerce/civil-services",
      },
    ],
  },
  {
    category: "Niche & Emerging Fields",
    options: [
      {
        title: "Fintech Expert",
        description: "Financial Technology Solutions",
        icon: "Code2",
        color: "blue-600",
        path: "/career/commerce/fintech",
      },
      {
        title: "Blockchain Finance",
        description: "Cryptocurrency and Blockchain",
        icon: "Code2",
        color: "purple-600",
        path: "/career/commerce/blockchain",
      },
      {
        title: "ESG Analyst",
        description: "Sustainable Finance and Investment",
        icon: "Leaf",
        color: "green-600",
        path: "/career/commerce/esg",
      },
      {
        title: "Wealth Manager",
        description: "Personal Finance and Investment",
        icon: "Banknote",
        color: "blue-600",
        path: "/career/commerce/wealth-manager",
      },
      {
        title: "Forensic Accountant",
        description: "Financial Investigation and Fraud Detection",
        icon: "Microscope",
        color: "red-600",
        path: "/career/commerce/forensic-accountant",
      },
      {
        title: "Data Analyst",
        description: "Financial Data Analysis",
        icon: "ChartBar",
        color: "purple-600",
        path: "/career/commerce/data-analyst",
      },
    ],
  },
];
