export const examOptions = [
  {
    category: "Humanities & Social Sciences",
    options: [
      {
        title: "CUET",
        description: "For admission to Central Universities",
        icon: "School",
        color: "indigo-600",
        path: "https://cuet.samarth.ac.in/",
      },
      {
        title: "JNUEE",
        description: "Jawaharlal Nehru University Entrance Exam",
        icon: "School",
        color: "blue-600",
        path: "https://www.jnu.ac.in/",
      },
      {
        title: "TISS NET",
        description: "Tata Institute of Social Sciences",
        icon: "School",
        color: "green-600",
        path: "https://www.tiss.edu/",
      },
      {
        title: "CLAT",
        description: "For BA LLB in top NLUs",
        icon: "Scale",
        color: "red-600",
        path: "https://consortiumofnlus.ac.in/",
      },
      {
        title: "AILET",
        description: "Law entrance for NLU Delhi",
        icon: "Scale",
        color: "blue-600",
        path: "https://nludelhi.ac.in/",
      },
      {
        title: "DUET",
        description: "Entrance for Delhi University courses",
        icon: "School",
        color: "purple-600",
        path: "https://admission.uod.ac.in/",
      },
      {
        title: "ISBF Entrance",
        description: "For economics and finance (University of London)",
        icon: "ChartBar",
        color: "green-600",
        path: "https://www.isbf.edu.in/",
      },
    ],
  },
  {
    category: "Design & Fine Arts",
    options: [
      {
        title: "NID DAT",
        description: "National Institute of Design",
        icon: "Palette",
        color: "orange-600",
        path: "https://www.nid.edu/",
      },
      {
        title: "NIFT",
        description: "National Institute of Fashion Technology",
        icon: "Shirt",
        color: "pink-600",
        path: "https://www.nift.ac.in/",
      },
      {
        title: "AIEED",
        description: "Arch Academy of Design Entrance",
        icon: "Palette",
        color: "purple-600",
        path: "https://www.arch.ac.in/",
      },
      {
        title: "UCEED",
        description: "For design (IIT Bombay & others)",
        icon: "Palette",
        color: "red-600",
        path: "https://www.uceed.iitb.ac.in/",
      },
      {
        title: "NATA",
        description: "Architecture entrance exam",
        icon: "Building2",
        color: "blue-600",
        path: "https://www.nata.in/",
      },
      {
        title: "CEED",
        description: "PG design entrance",
        icon: "Palette",
        color: "green-600",
        path: "https://www.ceed.iitb.ac.in/",
      },
    ],
  },
  {
    category: "Mass Communication",
    options: [
      {
        title: "IIMC Entrance",
        description: "Indian Institute of Mass Communication",
        icon: "Newspaper",
        color: "red-600",
        path: "https://www.iimc.nic.in/",
      },
      {
        title: "XIC OET",
        description: "Xavier Institute of Communications",
        icon: "Newspaper",
        color: "blue-600",
        path: "https://www.xaviercomm.org/",
      },
    ],
  },
];

export const degreeOptions = [
  {
    category: "Humanities & Social Sciences",
    options: [
      {
        title: "BA",
        description: "Bachelor of Arts",
        icon: "BookOpen",
        color: "blue-600",
        path: "/career/arts/ba",
      },
      {
        title: "BA (Hons)",
        description: "Specialized Arts Programs",
        icon: "BookOpen",
        color: "purple-600",
        path: "/career/arts/ba-hons",
      },
      {
        title: "B.Ed",
        description: "Bachelor of Education",
        icon: "GraduationCap",
        color: "green-600",
        path: "/career/arts/bed",
      },
      {
        title: "BA in Psychology",
        description: "Psychology and Human Behavior",
        icon: "Brain",
        color: "pink-600",
        path: "/career/arts/psychology",
      },
      {
        title: "BA in Sociology",
        description: "Society and Social Behavior",
        icon: "Users",
        color: "indigo-600",
        path: "/career/arts/sociology",
      },
      {
        title: "BA in Economics",
        description: "Economic Theory and Analysis",
        icon: "ChartBar",
        color: "green-600",
        path: "/career/arts/economics",
      },
      {
        title: "BA in Political Science",
        description: "Political Systems and Governance",
        icon: "Building2",
        color: "red-600",
        path: "/career/arts/political-science",
      },
      {
        title: "BA in History",
        description: "Historical Studies and Research",
        icon: "BookOpen",
        color: "brown-600",
        path: "/career/arts/history",
      },
      {
        title: "BA LLB",
        description: "5-year Integrated Law Program",
        icon: "Scale",
        color: "blue-600",
        path: "/career/arts/ba-llb",
      },
      {
        title: "BSW",
        description: "Bachelor of Social Work",
        icon: "Heart",
        color: "pink-600",
        path: "/career/arts/social-work",
      },
      {
        title: "B.A. Liberal Arts",
        description: "Interdisciplinary Arts Program",
        icon: "BookOpen",
        color: "purple-600",
        path: "/career/arts/liberal-arts",
      },
      {
        title: "B.A. Philosophy",
        description: "Philosophical Studies",
        icon: "Brain",
        color: "indigo-600",
        path: "/career/arts/philosophy",
      },
    ],
  },
  {
    category: "Design & Fine Arts",
    options: [
      {
        title: "BFA",
        description: "Bachelor of Fine Arts",
        icon: "Palette",
        color: "orange-600",
        path: "/career/arts/bfa",
      },
      {
        title: "B.Des",
        description: "Bachelor of Design",
        icon: "Palette",
        color: "pink-600",
        path: "/career/arts/design",
      },
      {
        title: "BVA",
        description: "Bachelor of Visual Arts",
        icon: "Palette",
        color: "purple-600",
        path: "/career/arts/visual-arts",
      },
    ],
  },
  {
    category: "Professional Programs",
    options: [
      {
        title: "BHM",
        description: "Bachelor of Hotel Management",
        icon: "Home",
        color: "red-600",
        path: "/career/arts/hotel-management",
      },
      {
        title: "BBA",
        description: "Bachelor of Business Administration",
        icon: "Briefcase",
        color: "blue-600",
        path: "/career/arts/bba",
      },
    ],
  },
  {
    category: "Mass Communication",
    options: [
      {
        title: "BJMC",
        description: "Bachelor of Journalism and Mass Communication",
        icon: "Newspaper",
        color: "red-600",
        path: "/career/arts/journalism",
      },
      {
        title: "BMM",
        description: "Bachelor of Mass Media",
        icon: "Newspaper",
        color: "blue-600",
        path: "/career/arts/mass-media",
      },
      {
        title: "BA in Film Studies",
        description: "Film and Media Studies",
        icon: "Film",
        color: "indigo-600",
        path: "/career/arts/film-studies",
      },
    ],
  },
];

export const careerOptions = [
  {
    category: "Education & Research",
    options: [
      {
        title: "Teacher",
        description: "School and College Teaching",
        icon: "GraduationCap",
        color: "blue-600",
        path: "/career/arts/teacher",
      },
      {
        title: "Professor",
        description: "University Teaching and Research",
        icon: "GraduationCap",
        color: "purple-600",
        path: "/career/arts/professor",
      },
      {
        title: "Researcher",
        description: "Social Sciences Research",
        icon: "Microscope",
        color: "green-600",
        path: "/career/arts/researcher",
      },
      {
        title: "Historian",
        description: "Historical Research and Analysis",
        icon: "BookOpen",
        color: "brown-600",
        path: "/career/arts/historian",
      },
      {
        title: "Economist",
        description: "Economic Analysis and Policy",
        icon: "ChartBar",
        color: "green-600",
        path: "/career/arts/economist",
      },
      {
        title: "Political Analyst",
        description: "Political Research and Analysis",
        icon: "Building2",
        color: "red-600",
        path: "/career/arts/political-analyst",
      },
    ],
  },
  {
    category: "Design & Creative Arts",
    options: [
      {
        title: "Graphic Designer",
        description: "Visual Communication Design",
        icon: "Palette",
        color: "orange-600",
        path: "/career/arts/graphic-design",
      },
      {
        title: "Fashion Designer",
        description: "Apparel and Textile Design",
        icon: "Shirt",
        color: "pink-600",
        path: "/career/arts/fashion-design",
      },
      {
        title: "Interior Designer",
        description: "Space Design and Decoration",
        icon: "Home",
        color: "purple-600",
        path: "/career/arts/interior-design",
      },
      {
        title: "UI/UX Designer",
        description: "User Interface and Experience Design",
        icon: "Palette",
        color: "blue-600",
        path: "/career/arts/ui-ux",
      },
    ],
  },
  {
    category: "Media & Communication",
    options: [
      {
        title: "Journalist",
        description: "News Reporting and Writing",
        icon: "Newspaper",
        color: "red-600",
        path: "/career/arts/journalist",
      },
      {
        title: "Content Writer",
        description: "Digital Content Creation",
        icon: "PenTool",
        color: "blue-600",
        path: "/career/arts/content-writer",
      },
      {
        title: "Social Media Manager",
        description: "Digital Marketing and Engagement",
        icon: "Share2",
        color: "indigo-600",
        path: "/career/arts/social-media",
      },
      {
        title: "Content Strategist",
        description: "Content Planning and Management",
        icon: "PenTool",
        color: "purple-600",
        path: "/career/arts/content-strategist",
      },
      {
        title: "Foreign Language Specialist",
        description: "Language Services and Translation",
        icon: "MessageSquare",
        color: "green-600",
        path: "/career/arts/language-specialist",
      },
    ],
  },
  {
    category: "Public Service & Administration",
    options: [
      {
        title: "Civil Services",
        description: "IAS, IPS, IFS, etc.",
        icon: "Building2",
        color: "green-600",
        path: "/career/arts/civil-services",
      },
      {
        title: "Public Relations Officer",
        description: "Corporate Communications",
        icon: "MessageSquare",
        color: "blue-600",
        path: "/career/arts/public-relations",
      },
      {
        title: "Human Resource Manager",
        description: "Personnel Management",
        icon: "Users",
        color: "purple-600",
        path: "/career/arts/hr",
      },
      {
        title: "Government Policy Expert",
        description: "Policy Analysis and Development",
        icon: "Building2",
        color: "red-600",
        path: "/career/arts/policy-expert",
      },
      {
        title: "NGO Coordinator",
        description: "Non-Profit Organization Management",
        icon: "Heart",
        color: "pink-600",
        path: "/career/arts/ngo-coordinator",
      },
    ],
  },
  {
    category: "Law & Social Work",
    options: [
      {
        title: "Lawyer",
        description: "Legal Practice and Advocacy",
        icon: "Scale",
        color: "red-600",
        path: "/career/arts/lawyer",
      },
      {
        title: "Social Worker",
        description: "Community Development",
        icon: "Heart",
        color: "pink-600",
        path: "/career/arts/social-work",
      },
      {
        title: "Counselor",
        description: "Career and Mental Health",
        icon: "MessageCircle",
        color: "blue-600",
        path: "/career/arts/counselor",
      },
      {
        title: "Psychologist",
        description: "Mental Health and Counseling",
        icon: "Brain",
        color: "purple-600",
        path: "/career/arts/psychologist",
      },
      {
        title: "Therapist",
        description: "Clinical and Counseling Services",
        icon: "Heart",
        color: "pink-600",
        path: "/career/arts/therapist",
      },
    ],
  },
  {
    category: "Hospitality & Tourism",
    options: [
      {
        title: "Hotel Manager",
        description: "Hotel and Hospitality Management",
        icon: "Home",
        color: "red-600",
        path: "/career/arts/hotel-manager",
      },
      {
        title: "Tourism Professional",
        description: "Travel and Tourism Services",
        icon: "Plane",
        color: "blue-600",
        path: "/career/arts/tourism",
      },
    ],
  },
];
