import {
  BookOpen,
  GraduationCap,
  Briefcase,
  ChartBar,
  Rocket,
  Microscope,
  School,
  Award,
  Building2,
  Plane,
  Shield,
  Ship,
  Code2,
  Brain,
  Calculator,
  Heart,
  Flask,
  Stethoscope,
  Leaf,
  Pill,
  Dna,
  TestTube,
} from "lucide-react";

export const examOptions = [
  {
    category: "Medical & Allied Health",
    options: [
      {
        title: "NEET-UG",
        description: "MBBS, BDS, BAMS, BHMS, BPT, B.Sc. Nursing, etc.",
        icon: "Stethoscope",
        color: "red-600",
        path: "https://nta.ac.in/NEET",
      },
      {
        title: "AIIMS MBBS",
        description: "Now via NEET",
        icon: "Heart",
        color: "pink-600",
        path: "https://www.aiimsexams.ac.in/",
      },
      {
        title: "JIPMER",
        description: "Now via NEET",
        icon: "Stethoscope",
        color: "blue-600",
        path: "https://jipmer.edu.in/",
      },
      {
        title: "ICAR AIEEA",
        description: "B.Sc. Agriculture, Animal Science, Horticulture",
        icon: "Leaf",
        color: "green-600",
        path: "https://icar.nta.nic.in/",
      },
      {
        title: "CUET",
        description: "For B.Sc. (Bio, Microbiology, Biotech, etc.)",
        icon: "School",
        color: "indigo-600",
        path: "https://cuet.samarth.ac.in/",
      },
    ],
  },
  {
    category: "Research & Science",
    options: [
      {
        title: "IISER Aptitude Test",
        description: "BS-MS program",
        icon: "Microscope",
        color: "blue-600",
        path: "https://www.iiseradmission.in/",
      },
      {
        title: "NEST",
        description: "NISER & UM-DAE CBS for research programs",
        icon: "TestTube",
        color: "orange-600",
        path: "https://www.nestexam.in/",
      },
    ],
  },
  {
    category: "Other Exams",
    options: [
      {
        title: "State CETs",
        description: "For Pharmacy, Nursing, etc.",
        icon: "Award",
        color: "purple-600",
        path: "https://cetcell.mahacet.org/ (Example)",
      },
      {
        title: "AFMC",
        description: "Armed Forces Medical College (via NEET)",
        icon: "Shield",
        color: "gray-600",
        path: "https://www.afmc.nic.in/",
      },
      {
        title: "DUET/IPU CET",
        description: "University-specific entrance exams",
        icon: "Building2",
        color: "blue-600",
        path: "https://ipu.admissions.nic.in/",
      },
    ],
  },
];

export const degreeOptions = [
  {
    category: "Medical & Healthcare",
    options: [
      {
        title: "MBBS",
        description: "Bachelor of Medicine and Bachelor of Surgery",
        icon: "Stethoscope",
        color: "red-600",
        path: "/career/pcb/mbbs",
      },
      {
        title: "BDS",
        description: "Bachelor of Dental Surgery",
        icon: "Stethoscope",
        color: "blue-600",
        path: "/career/pcb/bds",
      },
      {
        title: "BAMS",
        description: "Bachelor of Ayurvedic Medicine and Surgery",
        icon: "Leaf",
        color: "green-600",
        path: "/career/pcb/bams",
      },
      {
        title: "BHMS",
        description: "Bachelor of Homeopathic Medicine and Surgery",
        icon: "Leaf",
        color: "green-600",
        path: "/career/pcb/bhms",
      },
      {
        title: "BUMS",
        description: "Bachelor of Unani Medicine and Surgery",
        icon: "Leaf",
        color: "green-600",
        path: "/career/pcb/bums",
      },
      {
        title: "B.Sc. Nursing",
        description: "Bachelor of Science in Nursing",
        icon: "Heart",
        color: "pink-600",
        path: "/career/pcb/nursing",
      },
      {
        title: "BPT",
        description: "Bachelor of Physiotherapy",
        icon: "Heart",
        color: "blue-600",
        path: "/career/pcb/bpt",
      },
      {
        title: "BOT",
        description: "Bachelor of Occupational Therapy",
        icon: "Heart",
        color: "purple-600",
        path: "/career/pcb/bot",
      },
    ],
  },
  {
    category: "Pharmacy & Allied Sciences",
    options: [
      {
        title: "B.Pharm",
        description: "Bachelor of Pharmacy",
        icon: "Pill",
        color: "purple-600",
        path: "/career/pcb/b-pharm",
      },
      {
        title: "D.Pharm",
        description: "Diploma in Pharmacy",
        icon: "Pill",
        color: "blue-600",
        path: "/career/pcb/d-pharm",
      },
      {
        title: "B.Sc. (Hons)",
        description: "Biology, Microbiology, Biochemistry, Zoology, Botany",
        icon: "Microscope",
        color: "green-600",
        path: "/career/pcb/bsc-hons",
      },
      {
        title: "Integrated M.Sc.",
        description: "BS-MS Dual Degree Programs",
        icon: "Microscope",
        color: "blue-600",
        path: "/career/pcb/integrated-msc",
      },
    ],
  },
  {
    category: "Agriculture & Veterinary",
    options: [
      {
        title: "B.V.Sc.",
        description: "Bachelor of Veterinary Sciences",
        icon: "Heart",
        color: "red-600",
        path: "/career/pcb/bvsc",
      },
      {
        title: "B.Sc. Agriculture",
        description: "Agricultural Sciences",
        icon: "Leaf",
        color: "green-600",
        path: "/career/pcb/agriculture",
      },
      {
        title: "B.Sc. Horticulture",
        description: "Horticultural Sciences",
        icon: "Leaf",
        color: "green-600",
        path: "/career/pcb/horticulture",
      },
      {
        title: "B.Sc. Forestry",
        description: "Forestry and Environmental Sciences",
        icon: "Leaf",
        color: "green-600",
        path: "/career/pcb/forestry",
      },
    ],
  },
  {
    category: "Technology & Research",
    options: [
      {
        title: "B.Tech Biotechnology",
        description: "Biotechnology and Genetic Engineering",
        icon: "Dna",
        color: "blue-600",
        path: "/career/pcb/biotech",
      },
      {
        title: "BMLT",
        description: "Medical Lab Technology",
        icon: "Microscope",
        color: "purple-600",
        path: "/career/pcb/bmlt",
      },
    ],
  },
];

export const careerOptions = [
  {
    category: "Medical Field",
    options: [
      {
        title: "Doctor",
        description: "Medical Practitioner (MBBS)",
        icon: "Stethoscope",
        color: "red-600",
        path: "/career/pcb/doctor",
      },
      {
        title: "Dentist",
        description: "Dental Care Specialist (BDS)",
        icon: "Stethoscope",
        color: "blue-600",
        path: "/career/pcb/dentist",
      },
      {
        title: "Ayurvedic Doctor",
        description: "Traditional Medicine Practitioner (BAMS)",
        icon: "Leaf",
        color: "green-600",
        path: "/career/pcb/ayurveda",
      },
      {
        title: "Surgeon",
        description: "Medical Specialist",
        icon: "Stethoscope",
        color: "red-600",
        path: "/career/pcb/surgeon",
      },
      {
        title: "Physiotherapist",
        description: "Physical Therapy Specialist",
        icon: "Heart",
        color: "blue-600",
        path: "/career/pcb/physiotherapist",
      },
      {
        title: "Pharmacist",
        description: "Medication and Drug Expert",
        icon: "Pill",
        color: "purple-600",
        path: "/career/pcb/pharmacist",
      },
      {
        title: "Nurse",
        description: "Healthcare Professional",
        icon: "Heart",
        color: "pink-600",
        path: "/career/pcb/nurse",
      },
      {
        title: "Medical Lab Technician",
        description: "Laboratory Testing Specialist",
        icon: "Microscope",
        color: "blue-600",
        path: "/career/pcb/lab-technician",
      },
    ],
  },
  {
    category: "Research & Science",
    options: [
      {
        title: "Biologist",
        description: "Biological Research",
        icon: "Microscope",
        color: "green-600",
        path: "/career/pcb/biologist",
      },
      {
        title: "Microbiologist",
        description: "Microorganism Research",
        icon: "Microscope",
        color: "blue-600",
        path: "/career/pcb/microbiologist",
      },
      {
        title: "Biotechnologist",
        description: "Biotechnology Research",
        icon: "Dna",
        color: "purple-600",
        path: "/career/pcb/biotechnologist",
      },
      {
        title: "Genetic Engineer",
        description: "Genetic Research and Development",
        icon: "Dna",
        color: "blue-600",
        path: "/career/pcb/genetic-engineer",
      },
      {
        title: "Environmental Scientist",
        description: "Environmental Research",
        icon: "Leaf",
        color: "green-600",
        path: "/career/pcb/environmental-scientist",
      },
      {
        title: "Forensic Scientist",
        description: "Forensic Research",
        icon: "Microscope",
        color: "red-600",
        path: "/career/pcb/forensic-scientist",
      },
    ],
  },
  {
    category: "Agriculture & Allied",
    options: [
      {
        title: "Agriculture Scientist",
        description: "Agricultural Research",
        icon: "Leaf",
        color: "green-600",
        path: "/career/pcb/agriculture-scientist",
      },
      {
        title: "Horticulturist",
        description: "Plant Cultivation Expert",
        icon: "Leaf",
        color: "green-600",
        path: "/career/pcb/horticulturist",
      },
      {
        title: "Soil Conservationist",
        description: "Soil Management Expert",
        icon: "Leaf",
        color: "green-600",
        path: "/career/pcb/soil-conservationist",
      },
      {
        title: "Food Technologist",
        description: "Food Science Expert",
        icon: "Flask",
        color: "orange-600",
        path: "/career/pcb/food-technologist",
      },
    ],
  },
  {
    category: "Other Careers",
    options: [
      {
        title: "Dietician",
        description: "Nutrition and Diet Expert",
        icon: "Heart",
        color: "pink-600",
        path: "/career/pcb/dietician",
      },
      {
        title: "Psychologist",
        description: "Mental Health Professional",
        icon: "Brain",
        color: "purple-600",
        path: "/career/pcb/psychologist",
      },
      {
        title: "Science Writer",
        description: "Scientific Content Creation",
        icon: "BookOpen",
        color: "blue-600",
        path: "/career/pcb/science-writer",
      },
      {
        title: "Lab Manager",
        description: "Laboratory Administration",
        icon: "Microscope",
        color: "gray-600",
        path: "/career/pcb/lab-manager",
      },
      {
        title: "Public Health Officer",
        description: "Public Health Management",
        icon: "Heart",
        color: "red-600",
        path: "/career/pcb/public-health",
      },
      {
        title: "Hospital Administrator",
        description: "Healthcare Facility Management",
        icon: "Briefcase",
        color: "orange-600",
        path: "/career/pcb/hospital-admin",
      },
    ],
  },
];
